---
- name: Set up the Nodesource RPM directory for Node.js
  set_fact:
    nodejs_rhel_rpm_dir: "pub_{{ nodejs_version }}"

- name: Import Nodesource RPM key.
  rpm_key:
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present

- name: Add Nodesource repositories for Node.js.
  template:
    src: nodesource-el.repo.j2
    dest: /etc/yum.repos.d/nodesource-el.repo
    mode: 0644

- name: Ensure Node.js and npm are installed.
  yum: "name=nodejs-{{ nodejs_version[0] }}.* state=present enablerepo='epel,nodesource'"
